//PRUEBA SIN AUTENTICACION
### GET request to example server
GET http://localhost:8080/transacciones

//REGISTRO USUARIO
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "gema_pro",
  "email": "gema@zenit.com",
  "password": "password123"
}

### Prueba de Login
//LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "gema@zenit.com",
  "password": "password123"
}

> {% client.global.set("token_actual", response.body.token); %}

### Prueba de acceso a ruta protegida
GET http://localhost:8080/transacciones
Authorization: Bearer {{token_actual}}

### Crear una nueva transacción (Gasto)
POST http://localhost:8080/transacciones
Authorization: Bearer {{token_actual}}
Content-Type: application/json

{
  "monto": 25.50,
  "descripcion": "Cena de viernes",
  "tipo": "GASTO",
  "categoriaId": 1
}

### Borrar una transacción
DELETE http://localhost:8080/transacciones/11
Authorization: Bearer {{token_actual}}

### Editar una transacción
PUT http://localhost:8080/transacciones/10
Authorization: Bearer {{token_actual}}
Content-Type: application/json

{
  "monto": 50.0,
  "descripcion": "Cena editada",
  "tipo": "GASTO",
  "categoriaId": 1
}

### Obtener lista de categorías para los desplegables
//CATEGORIAS
GET http://localhost:8080/categorias
Authorization: Bearer {{token_actual}}

### Crear una nueva categoría personalizada
POST http://localhost:8080/categorias
Authorization: Bearer {{token_actual}}
Content-Type: application/json

{
  "nombre": "Salud",
  "icono": "fitness_center"
}

### Obtener resumen del mes actual
//PARA LAS ESTADISTICAS
GET http://localhost:8080/stats/resumen
Authorization: Bearer {{token_actual}}

//METAS
### Crear una meta
POST http://localhost:8080/metas
Authorization: Bearer {{token_actual}}
Content-Type: application/json

{
  "nombre": "Coche nuevo",
  "objetivo": 5000.0,
  "fechaLimite": "2026-12-31"
}

### Ver mis metas
GET http://localhost:8080/metas
Authorization: Bearer {{token_actual}}

//PRESUPUESTOS
### 1. Crear un presupuesto para una categoría (ej: Comida)
POST http://localhost:8080/presupuestos
Authorization: Bearer {{token_actual}}
Content-Type: application/json

{
  "montoLimite": 300.0,
  "categoriaId": 1,
  "mes": 4,
  "anio": 2026
}

### 2. Obtener todos mis presupuestos configurados
GET http://localhost:8080/presupuestos
Authorization: Bearer {{token_actual}}